apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  annotations:
    github.com/project-slug: enyoquiga/python-app
spec:
  type: other
  lifecycle: unknown
  owner: development
